# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_foiarequestdata import FOIARequestData
from ..types.enums.enm_recordsstatus import RecordsStatus
from ..types.enums.enm_requeststatus import RequestStatus
from baml_lib._impl.functions import BaseBAMLFunction
from typing import Protocol, runtime_checkable


IExtractRequestDataOutput = FOIARequestData

@runtime_checkable
class IExtractRequestData(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        FOIARequestData
    """

    async def __call__(self, arg: str, /) -> FOIARequestData:
        ...


class IBAMLExtractRequestData(BaseBAMLFunction[FOIARequestData]):
    def __init__(self) -> None:
        super().__init__(
            "ExtractRequestData",
            IExtractRequestData,
            ["v1"],
        )

    async def __call__(self, *args, **kwargs) -> FOIARequestData:
        return await self.get_impl("v1").run(*args, **kwargs)

BAMLExtractRequestData = IBAMLExtractRequestData()

__all__ = [ "BAMLExtractRequestData" ]
