# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_paymentvalidationdata import PaymentValidationData
from ..types.partial.classes.cls_paymentvalidationdata import PartialPaymentValidationData
from baml_core.stream import AsyncStream
from typing import Callable, Protocol, runtime_checkable


import typing

import pytest
from contextlib import contextmanager
from unittest import mock

ImplName = typing.Literal["v1"]

T = typing.TypeVar("T", bound=typing.Callable[..., typing.Any])
CLS = typing.TypeVar("CLS", bound=type)


IPaymentValidationOutput = PaymentValidationData

@runtime_checkable
class IPaymentValidation(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        PaymentValidationData
    """

    async def __call__(self, arg: str, /) -> PaymentValidationData:
        ...

   

@runtime_checkable
class IPaymentValidationStream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        arg: str

    Returns:
        AsyncStream[PaymentValidationData, PartialPaymentValidationData]
    """

    def __call__(self, arg: str, /) -> AsyncStream[PaymentValidationData, PartialPaymentValidationData]:
        ...
class BAMLPaymentValidationImpl:
    async def run(self, arg: str, /) -> PaymentValidationData:
        ...
    
    def stream(self, arg: str, /) -> AsyncStream[PaymentValidationData, PartialPaymentValidationData]:
        ...

class IBAMLPaymentValidation:
    def register_impl(
        self, name: ImplName
    ) -> typing.Callable[[IPaymentValidation, IPaymentValidationStream], None]:
        ...

    async def __call__(self, arg: str, /) -> PaymentValidationData:
        ...

    def stream(self, arg: str, /) -> AsyncStream[PaymentValidationData, PartialPaymentValidationData]:
        ...

    def get_impl(self, name: ImplName) -> BAMLPaymentValidationImpl:
        ...

    @contextmanager
    def mock(self) -> typing.Generator[mock.AsyncMock, None, None]:
        """
        Utility for mocking the PaymentValidationInterface.

        Usage:
            ```python
            # All implementations are mocked.

            async def test_logic() -> None:
                with baml.PaymentValidation.mock() as mocked:
                    mocked.return_value = ...
                    result = await PaymentValidationImpl(...)
                    assert mocked.called
            ```
        """
        ...

    @typing.overload
    def test(self, test_function: T) -> T:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the PaymentValidationInterface.

        Args:
            test_function : T
                The test function to be decorated.

        Usage:
            ```python
            # All implementations will be tested.

            @baml.PaymentValidation.test
            async def test_logic(PaymentValidationImpl: IPaymentValidation) -> None:
                result = await PaymentValidationImpl(...)
            ```
        """
        ...

    @typing.overload
    def test(self, *, exclude_impl: typing.Iterable[ImplName] = [], stream: bool = False) -> pytest.MarkDecorator:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the PaymentValidationInterface.

        Args:
            exclude_impl : Iterable[ImplName]
                The names of the implementations to exclude from testing.
            stream: bool
                If set, will return a streamable version of the test function.

        Usage:
            ```python
            # All implementations except the given impl will be tested.

            @baml.PaymentValidation.test(exclude_impl=["implname"])
            async def test_logic(PaymentValidationImpl: IPaymentValidation) -> None:
                result = await PaymentValidationImpl(...)
            ```

            ```python
            # Streamable version of the test function.

            @baml.PaymentValidation.test(stream=True)
            async def test_logic(PaymentValidationImpl: IPaymentValidationStream) -> None:
                async for result in PaymentValidationImpl(...):
                    ...
            ```
        """
        ...

    @typing.overload
    def test(self, test_class: typing.Type[CLS]) -> typing.Type[CLS]:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the PaymentValidationInterface.

        Args:
            test_class : Type[CLS]
                The test class to be decorated.

        Usage:
        ```python
        # All implementations will be tested in every test method.

        @baml.PaymentValidation.test
        class TestClass:
            def test_a(self, PaymentValidationImpl: IPaymentValidation) -> None:
                ...
            def test_b(self, PaymentValidationImpl: IPaymentValidation) -> None:
                ...
        ```
        """
        ...

BAMLPaymentValidation: IBAMLPaymentValidation
