# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from baml_lib._impl.deserializer import register_deserializer
from enum import Enum


@register_deserializer({  })
class RecordsStatus(str, Enum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    RECORDS_FOUND = "RECORDS_FOUND"
    NO_RECORDS_FOUND = "NO_RECORDS_FOUND"
    MORE_RECORDS_PENDING = "MORE_RECORDS_PENDING"
